### ISSUE TITLE
Py3 compatibility

### ISSUE THREAD

**Issue by clbarnes** [funkey/gunpowder#25]
https://pythonclock.org/

I got the tests to pass with a single change in `nodes/chunk.py` and a couple of coercions to integer in the test code.

If there's good reasons (like dependency issues) for keeping things old school, that's fine (and it'd be good to document that here, and in the README and other docs), but if it's not likely to be huge amounts of work then I can give it a crack.

Points for clarification:
- [ ] Classic division. I've imported future division in every file which did any division, for consistency - it seems from existing coercions that true division is wanted practically all of the time anyway. The only case where I'm not sure this is true is in Coordinate (division dunder methods) and Roi (`get_center`).

**Comment by funkey** [comment]
Thanks a lot for looking into that. The current development branch is [`release-v0.3`](https://github.com/funkey/gunpowder/tree/release-v0.3), I think it would be best to make this one Python 3 compatible as it will replace `master` soon.

In this branch, `Coordinate` is also restricted to hold integer values, which means we'd want floor divisions there.

**Comment by clbarnes** [comment]
> `Coordinate` is also restricted to hold integer values

Excellent, that answered another of my questions. I'll take a look.

**Comment by clbarnes** [comment]
In terms of expected behaviour: should all divisions of a Coordinate or ROI round towards negative infinity and produce an integer? If they are intended to support world coordinates at some point, true division will be required, but if they're pixel-spaced for now maybe holding them to integers is what's wanted.

Maybe a WorldCoord/WorldROI would be the way forward later.

**Comment by funkey** [comment]
Yes, Coordinate and ROI should always be integer, and round to floor.

They are already used to represent world units, deliberately forcing integer. The reason is that otherwise the definition of intervals gets tricky: We want to be able to express half-open ranges `[begin,end)` unambiguously. Having integer coordinates makes that easier, and for all the examples we encountered so far, world units could easily be scaled such that they are integer. Note that this only applies to `Array`s, i.e., data that already lies on a grid. For `Points`, the location is allowed to be float (we don't use `Coordinate` for point locations, but a simple `ndarray` of float).

**Comment by funkey** [comment]
`gunpowder` is, since (at least?) v1.0, Python 3 compatible. Thanks for bringing this up!
