### ISSUE TITLE
Artifact in output N5 for all-zero blocks

### ISSUE THREAD

**Issue by aschampion** [funkey/gunpowder#61]
Some all-zero blocks in N5 volumes created by `N5Write` erroneously contain part of the last non-zero block in the batch data array (in scan order).

![n5_anomoly](https://user-images.githubusercontent.com/460206/57463427-b204ad80-7272-11e9-930e-1497fd620b61.png)

This does not occur for `Hdf5Write`, so is not in the data array itself, and I've verified it's actually in the N5 and not a bug in BDV/n5-view.

z5py version 1.4.1

It seems most likely to be an artifact from `Hdf5LikeWrite`/z5py slicing/broadcasting or empty/uniform fill value block optimization. cc @constantinpape 

I'll try to create a minimal reproduction, but wanted to create an issue first in case anyone else has encountered this.

**Comment by constantinpape** [comment]
This indeed might be an issue in z5 when writing empty chunks. 
My guess is that this happens because some internal buffer is not cleared properly.
Also, this might only happen when the access via `[]` is not aligned with the chunks.
(Which makes handling the buffers more complicated and error prone).

Would be great if you could find a minimal example for this and then make an issue in the z5 repo!

**Comment by aschampion** [comment]
Confirmed to be a z5py issue in constantinpape/z5#106. Closing this.
